redhat-developer/vscode-server-connector

package.json, src/extension.ts
=> Add context menu for servers view items

Jenkinsfile, README.md, package.json
build pipeline, builds are archived on jenkins master for now
=> Add jenkinsfile for builds

src/serverExplorer.ts
=> Update server name template to name:type (status)

src/serverExplorer.ts
build is red because of tsc complaining, fixes that
=> Remove unused import to appease tsc

package-lock.json, package.json
=> Fix NPM vulnerabilities

LICENSE
=> add EPL 1.0

src/extension.ts, src/serverExplorer.ts, src/test/extension.test.ts, tslint.json
=> update tslint and changes to source files

src/extension.ts, src/protocol.ts, src/serverExplorer.ts
Fix #23 
1. Added `ServerSpecificType` field
2. Changed `id` to accept just name and request to server
3. Prompt validations for `server name input field`.
=> server name prompt validations

package.json, src/extension.ts, src/serverExplorer.ts
=> Add server visible name in Tree Explorer List

.vscodeignore, package-lock.json, package.json, src/extension.ts, src/protocol.ts, src/server.ts
Depends on https://github.com/robstryker/org.jboss.tools.ssp/pull/23
=> Migrate to latest ssp api and get ready to start server inside ext

package-lock.json, src/extension.ts, src/server.ts
=> Fix java filename path for different platforms

README.md
=> update readme in sync with latest command supports

src/serverExplorer.ts
=> Fix errors when folder selection dialog and name prompt are canceled

src/extension.ts
requires fix to apply in ssp server https://github.com/robstryker/org.jboss.tools.ssp/pull/34 to work properly,
=> Fix ssp-client migration problems

package-lock.json, package.json, src/extension.ts, src/protocol.ts, src/serverExplorer.ts
This is the initial implementation to use SSPCLient module in VSCode. Some issues are there in [ssp-client](https://github.com/sudhirverma/ssp-client/issues/10) which needs to be fixed for this to be working.
=> Migrate to use ssp-client npm module

CHANGELOG.md, README.md, package-lock.json, package.json
=> Fix files with new repo link

package.json, src/extension.ts, src/serverExplorer.ts
=> command palette for stop/remove server

package.json, test/index.ts
=> Update deps include mocha reporter and enable it when running on jenkins

README.md
=> update README with server actions

package-lock.json, package.json, src/extension.ts, src/serverExplorer.ts
=> Restart action for server

build/package.js, package-lock.json, package.json, src/extension.ts, src/server.ts, src/serverExplorer.ts
=> use latest rsp-client

README.md, package-lock.json, package.json, test/index.ts
=> Bump version for rsp-client

package-lock.json, package.json, src/extension.ts, src/serverExplorer.ts, test/serverExplorer.test.ts
=> Unittest for serverExplorer.ts file

build/package.js
=> Update link from ssp to rsp distribution zip

package.json
=> Add onCommand activation events for all commands from extension

package-lock.json, package.json, src/serverExplorer.ts, test/serverExplorer.test.ts
- code deduping
- nested suites
- duplicate tests replaced
- type checks for fakes
- general formatting improvements
=> Clean up ServerExplorer tests

README.md
=> Add animate gif(s) for the extension

package-lock.json, test/extension.test.ts
=> Added test for extension.ts 

package-lock.json, package.json, src/extension.ts, src/server.ts
=> start rsp-server with random available port

src/extension.ts, src/serverExplorer.ts, test/commands.test.ts, test/extension.test.ts, test/serverExplorer.test.ts
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
=> Issue #156: Already existing servers are not displayed in the Servers view

build/package.js
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
=> Use 0.10.0.Final

src/serverExplorer.ts, test/serverExplorer.test.ts
=> Fix When location selection dialog is canceled it shows error message

CONTRIBUTING.md
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
=> #183: Add CONTRIBUTING guide

src/server.ts
=> Use rsp server location from env var RS_SERVER_LOCATION if defined

.travis.yml, Jenkinsfile, package.json
=> Add build script to run all prep steps before creating extension pacakge

src/extension.ts, src/server.ts
=> Remove process instance from extension public API

build/package.js
=> use rsp-server 0.13.0.Final

package.json
=> bump version to 0.13.0 to match rsp-server

Jenkinsfile
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
=> Add publish to markeplace to Jenkinsfile

package-lock.json, package.json, src/extension.ts, src/extensionApi.ts, src/requirements.ts, src/server.ts
=> [220] allow configure jdk, prompt to download jdk if not present

package.json
so it shows up directly in the VS Code marketplace
=> Add link to issue tracker

src/extensionApi.ts, src/server.ts, test/commands.test.ts
=> [222] client connects twice

test/serverExplorer.test.ts
=> Compilation error

src/extension.ts, src/server.ts, src/serverExplorer.ts, test/extension.test.ts
=> Work in progress

build/package.js
=> Use rsp-server 0.13.1-SNAPSHOT in builds

build/package.js
=> Update to use 0.13.1.Final service release

package.json
=> use rsp-client 0.13.0

package.json, src/requirements.ts
=> Update error language and upversion to 0.13.1

src/extensionApi.ts
=> Show Output Channel throw error when there is nothing to select

src/extensionApi.ts
=> Remove, start, stop and restart  command throw error if we don't select any thing from command palette

build/package.js
=> Use rsp-server 0.13.2-SNAPSHOT

src/editorutil.ts, src/extensionApi.ts
=> Make sure large prompts show up in an editor

src/server.ts, src/serverExplorer.ts
=> fixing lint errors

src/extensionApi.ts
=> [261] dont error if user cancels runtime selection

src/extensionApi.ts, src/serverExplorer.ts
=>  [267] allow users to cancel inputs

build/package.js, package.json, src/extension.ts, src/extensionApi.ts, src/serverExplorer.ts, test/commands.test.ts, test/extension.test.ts, test/serverExplorer.test.ts, test/stubs.ts
=> Support secret input fields

src/serverExplorer.ts, test/serverExplorer.test.ts
this depends on rsp-client 0.14 which currently isn't released yet.
=> fixed serverExplorer test

src/extensionApi.ts
=> [281] dont access string if it's undefined

src/extensionApi.ts, src/serverExplorer.ts
=> [287] reject without message if user cancels creating a server

build/package.js
=> Update rsp-server url as changed in rsp-server jenkinsfile (issue 195)

build/package.js, src/extension.ts, src/extensionApi.ts, src/jobprogress.ts, test/commands.test.ts, test/jobprogress.test.ts, test/stubs.ts
=>  display progress and allow cancelling when downloading server

src/extensionApi.ts, test/commands.test.ts
=> [282] ask for confirmation before removing a server

.vscode/settings.json, package.json, src/extension.ts, src/extensionApi.ts, tslint.json
=> [294] configured vscode config for indentation, added tslint-eslint-rules

package-lock.json, package.json, src/serverExplorer.ts
=> Update to allow sending deployment options

build/package.js
=> Upversion to 0.15.0.Final

src/extensionApi.ts
=> [307] increased timeout for listing downloadable runtimes

src/extensionApi.ts
=> #309 downloadable runtimes should be sorted in a natural way

src/serverExplorer.ts, test/serverExplorer.test.ts
it fixes #316 
Signed-off-by: Luca Stocchi lstocchi@redhat.com
=> [316] check if server type has some value before sending request to server

build/package.js
=> bump server to 0.15.1.Final

src/serverExplorer.ts
it fixes #331 
Signed-off-by: Luca Stocchi lstocchi@redhat.com
=> [331] fixed addDeployment label

src/serverExplorer.ts
=> [337] only prompt for deployment type on windows

src/serverExplorer.ts
=> [341] Cannot choose a file in linux native dialog, folder only

build/package.js, package.json
=> [330] using rsp-server 0.16.0-SNAPSHOT and bumping to 0.16.0

src/serverExplorer.ts
=> fixed error when adding new deployment to server (#330)

test/serverExplorer.test.ts
=> added tests to check filedialog options on different OSes (#344)

src/extension.ts
it fixes #313 
Signed-off-by: Luca Stocchi lstocchi@redhat.com
=> [313] Error "Connection is closed" wont tell the user what exactly and why it failed

package-lock.json, package.json, test/commands.test.ts, test/protocolstubs.ts, test/serverExplorer.test.ts
related to https://github.com/redhat-developer/rsp-client/pull/87 and https://github.com/redhat-developer/rsp-client/pull/89
=> require rsp-client 0.16.0

package.json, src/serverExplorer.ts, test/protocolstubs.ts, test/serverExplorer.test.ts
=> display new status Debugging when server is started in debug mode (#333)

package-lock.json, package.json, src/editorutil.ts, src/extension.ts, src/extensionApi.ts, src/serverEditorAdapter.ts, src/serverExplorer.ts, src/utils.ts, test/extension.test.ts
it fixes #352 
Solution still incomplete, need to fix some minor things but I'm creating this PR so you can start checking it due to the limited time we have left. Hopefully you will have some idea to improve it. 
Currently i'm using temp files because i wasn't able to store the json in-memory. Virtual documents seem that are not a valid solution for our purpose. Already opened a issue so we can investigate more later #353
=> Added editor to allow user change server properties (#352)

.vscode/extensions.json
=> replaced tslint with typescript-tslint-plugin, added java-pack (#360)

package.json
=> changed visibility Download Server and Add Local Server commands in ctx menu (#367)

build/package.js, package.json
=> Update to consume 0.20.1 rsp-server

README.md
it fixes #384 
I added the new commands created in last months. Should we also add CDK in supported server? Don't know if there is a reason we didn't write it before
=> updated read.me file (#384)

package.json
this PR is related to #363 
Any other idea/suggestion to improve extension visibility in marketplace is appreciated.
=> update keywords and description in package.json (#363)

build/package.js, package-lock.json, package.json
=> Use distribution 0.20.2.Final

src/server.ts
=> Fixes #393 - pass in an rsp-id for this extension

build/package.js, package.json
=> Forgot to depend on rsp-server 0.21.0 final

package.json, src/extensionApi.ts, src/server.ts, test/server.test.ts
=> Make sure RSP is marked as stopped if terminated

build/package.js
=> Update bundled server to 0.21.1-SNAPSHOT

src/server.ts
=> added range to portfinder (#400)

package-lock.json, package.json, src/server.ts
=> Check if workspace is locked (#403)

package-lock.json, package.json
=> Fixing broken structure for new test layout

package-lock.json, package.json, test/index.debug.ts, test/test-runner.ts
- fixing adapters build
- updated package.json, package-lock
- removed vscode dependency
=> Move to vscode-test

build/package.js, package.json
@jeffmaury you can merge this for new version
=> updated url rsp server jar + bump extension version

package.json
=> added new view to activation events (#414)

build/package.js
=> Update to 0.22.2.Final rsp-server

src/server.ts
=> Fixes #420 - properly configure portFinder

README.md
=> Fixes #419 - Update readme to show support for crc / eap72

build/package.js, package.json
=> Upversion to 0.22.5, include distro of same version

build/package.js, package.json
=> Upversion to 0.22.8 and use newest rsp-server

package-lock.json, package.json, src/server.ts
=> Fixes #432 - termintae doesn't terminate

.gitignore, .vscode/launch.json, package.json, src/ui-test/.mocharc-debug.js, src/ui-test/allTestsSuite.ts, src/ui-test/common/adaptersContants.ts, src/ui-test/common/serverContants.ts, src/ui-test/common/serverState.ts, src/ui-test/rspServerProviderOperationsTest.ts, src/ui-test/rspServerProviderUITest.ts, src/ui-test/server/serverUtils.ts, src/ui-test/server/ui/rspServerProvider.ts, src/ui-test/server/ui/serversActivityBar.ts
- testing rsp provider actions and UI
=> Implementing RSP server provider UI tests

Jenkinsfile, build/package.js
Builds snapshots with latest RSP snapshot, releases with latest stable RSP.
=> Bundle latest snapshot/stable RSP

package.json, src/ui-test/rspServerProviderOperationsTest.ts, src/ui-test/rspServerProviderUITest.ts, src/ui-test/server/serverUtils.ts, src/ui-test/server/ui/rspServerProvider.ts, src/ui-test/server/ui/serversActivityBar.ts
=> Upgrade vscode-extension-tester to 3.0.0

package-lock.json, package.json
=> Upversion to 0.22.11 for release

package.json
=> Fix tests by using vscode 1.46.0

package-lock.json, src/ui-test/.mocharc-debug.js, src/ui-test/basicServerTest.ts, src/ui-test/rspServerProviderOperationsTest.ts, src/ui-test/server/ui/abstractServer.ts
=> Adapt UI tests to updated rsp-ui

package.json
=> Upversion to 0.23.3 to consume rsp-server 0.23.4

Jenkinsfile
=> Add odockal and lstocchi as submitters for publishing

.travis.yml, src/ui-test/extensionUITest.ts
=> Fix ui-test due to vscode ui change

package-lock.json, package.json
=> Upversion to 0.23.5, consume latest rsp-server

src/ui-test/basicServerTest.ts, src/ui-test/common/util/downloadServerUtil.ts, src/ui-test/common/util/serverUtils.ts
=> Refactor handling of native file manager dialog

.vscodeignore
=> Omit ui-test in out folder so it is not packed in vsix

.github/workflows/gh-actions.yml, Jenkinsfile, package-lock.json, package.json, test/index.debug.ts, test/ui-test/advancedServerTest.ts, test/ui-test/common/constants/adaptersContants.ts, test/ui-test/common/constants/serverConstants.ts, test/ui-test/common/dialog/closeEditorDialog.ts, test/ui-test/common/util/testUtils.ts, test/ui-test/custom-settings.json, test/ui-test/extensionUITest.ts, test/ui-test/rspServerProviderActionsTest.ts, test/ui-test/rspServerProviderUITest.ts, test/ui-test/server/ui/abstractServer.ts, test/ui-test/server/ui/deployment.ts, test/ui-test/server/ui/rspServerProvider.ts, test/ui-test/server/ui/server.ts
=> UI tests stabilization

README.md
=> Correct the name of CRC

pr/Jenkinsfile
=> Draft: Add PR check Jenkinsfile

package.json, test/ui-test/advancedServerTest.ts, test/ui-test/common/util/testUtils.ts, test/ui-test/server/ui/deployment.ts
=> fixing failing remove deployment context menu item action

package-lock.json, test/ui-test/basicServerTest.ts, test/ui-test/common/ui/webViewForm.ts, test/ui-test/common/util/downloadServerUtil.ts, test/ui-test/common/util/testUtils.ts, test/ui-test/server/ui/abstractServer.ts, test/ui-test/server/ui/rspServerProvider.ts, test/ui-test/server/ui/serverCreationForm.ts
=> Implement web wizard support in UI tests

package-lock.json, package.json, test/ui-test/advancedServerOperationTest.ts, test/ui-test/advancedServerTest.ts, test/ui-test/allTestsSuite.ts, test/ui-test/basicServerTest.ts, test/ui-test/common/constants/serverConstants.ts, test/ui-test/common/ui/webViewForm.ts, test/ui-test/common/util/testUtils.ts, test/ui-test/publicTestsSuite.ts, test/ui-test/rspServerProviderActionsTest.ts, test/ui-test/rspServerProviderUITest.ts, test/ui-test/server/ui/abstractServer.ts, test/ui-test/server/ui/rspServerProvider.ts, test/ui-test/server/ui/server.ts, test/ui-test/serverTestOperator.ts
-  update wf servers to tests
-  refactoring
=> Introduce Edit Server UI tests

test/ui-test/advancedServerOperationTest.ts
=> Add UI Tests for server actions, fixes #496

Jenkinsfile, package-lock.json
=> No strict ssl for npm packages on internal network

.github/workflows/gh-actions.yml, package-lock.json, package.json, test/ui-test/basicServerTest.ts, test/ui-test/common/constants/serverConstants.ts, test/ui-test/rspServerProviderActionsTest.ts
=> Update extension-tester to 4.3.0, update wf server to 26

Jenkinsfile, package-lock.json, package.json, test/ui-test/basicServerTest.ts
=> Update dependencies, mocha among one of them

package.json
=> Re-enable the ui tests
